version: '3.9'
services:
  backend:
    build: .
    port:
      - 3334:3334
    volumes:
      - .:/app

  db:
    image: postgres:1.1.11
    restart: always
    environment:
      POSTGRES_DATABASE: shop_udemy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
